### PR TITLE
[Issue #26] Adding flag for horizontal and vertical swiping

### LINKED ISSUE #26: Make it possible to disable vertical (up/down) swiping
Hello, would it be possible to add the ability to disable vertical swiping, so that the user may only swipe left or right, but not up or down? Thanks!

### PR DESCRIPTION
**Pull request by mlabisi**
Addresses / Fixes #26 

This PR adds two flags, `horizontalSwipeEnabled` and `verticalSwipeEnabled`!

### CODE REVIEW

**Comment by mlabisi** [comment]
Sorry about the spacing/formatting changes! My IDE automatically added them. Let me know if I should revert those.

**Comment by M-S-KHAN** [comment]
Much required. Please approve the PR @bilalhamud

**Review by M-S-KHAN — APPROVED** [review]

**Comment by simplenotezy** [comment]
Thanks for the PR @mlabisi - would love to get that in! 😊

**Comment by phongnd93** [comment]
Thanks for the PR @mlabisi - hope this PR is released soon 😊

**Review by Alii-isk — APPROVED** [review]

**Comment by Alii-isk** [comment]
> Thanks for the PR @mlabisi - would love to get that in! 😊

**Comment by vvanan158** [comment]
`  void _onEndAnimation() {
    if ((_left < -widget.threshold || _left > widget.threshold) &&
        widget.horizontalSwipeEnabled) {
      _swipeHorizontal(context);
    } else if ((_top < -widget.threshold || _top > widget.threshold) &&
        widget.verticalSwipeEnabled) {
      _swipeVertical(context);
    } else {
      _goBack(context);
    }
  }`

  
thanks. it work for me.

**Comment by vvanan158** [comment]
```
  void _onEndAnimation() {
    if ((_left < -widget.threshold || _left > widget.threshold) &&
        widget.horizontalSwipeEnabled) {
      _swipeHorizontal(context);
    } else if ((_top < -widget.threshold || _top > widget.threshold) &&
        widget.verticalSwipeEnabled) {
      _swipeVertical(context);
    } else {
      _goBack(context);
    }
  }
```
Thanks, it work for me :)

**Comment by clarson15** [comment]
any update on this?

**Comment by mlabisi** [comment]
I’ll need approval from the repo owner in order for this PR to be merged 😅On Jan 29, 2023, at 7:08 PM, Charles Larson ***@***.***> wrote:﻿
any update on this?

**Comment by bilalhamud** [comment]
Implemented among other features with version 2.0.0

**Pull request closed without merging**
