### PR TITLE
feature: addedd onDrag callback

### PR DESCRIPTION
**Pull request by simplenotezy**
Feature
-
This PR introduces an `onDrag(double left, double top)` callback function that can be used if needed.

It allows for more complex animations, such as adding an overlay to the card, once being dragged, or animating the buttons to increase in size depending on the direction the card is being dragged in

### CODE REVIEW

**Comment by simplenotezy** [comment]
@bilalhamud I know you guys must be super busy, but any chance we could get this merged? We'd love to use it for [Doubble](https://doubble.app)

**Comment by bilalhamud** [comment]
Hey @simplenotezy, thanks for contributing to our package, will check it out this week

**Comment by IlgamGabdullin** [comment]
Hi! Is there any updates? waiting for this pr to be merged

**Comment by khanmujeeb687** [comment]
Hey @IlgamGabdullin , This feature is already live.

**Pull request closed without merging**
